#!/usr/bin/env bash
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
say()  { echo -e "${GREEN}[buildit]${NC} $*"; }
warn() { echo -e "${YELLOW}[buildit]${NC} $*"; }
die()  { echo -e "${RED}[buildit]${NC} $*"; exit 1; }

PROJ_DIR="$(cd "$(dirname "$0")" && pwd)"
say "SKIPPY build script"
say "project dir: ${PROJ_DIR}"

# ── 0. detect os → runtime id ─────────────────────────────────
say "checking dotnet sdk..."
command -v dotnet >/dev/null 2>&1 || die "dotnet sdk not found. install: https://dotnet.microsoft.com/download"
DOTNET_VER=$(dotnet --version 2>/dev/null || echo "???")
say "dotnet sdk: v${DOTNET_VER}"

OS=$(uname -s)
ARCH=$(uname -m)

case "$OS" in
    Linux)
        say "detected: linux"
        case "$ARCH" in
            x86_64|amd64)  RID="linux-x64"   ;;
            aarch64|arm64) RID="linux-arm64"  ;;
            *) warn "unknown arch $ARCH, defaulting to linux-x64"; RID="linux-x64" ;;
        esac
        ;;
    Darwin)
        say "detected: macos"
        case "$ARCH" in
            x86_64|amd64)  RID="osx-x64"    ;;
            arm64|aarch64) RID="osx-arm64"  ;;
            *) warn "unknown arch $ARCH, defaulting to osx-x64"; RID="osx-x64" ;;
        esac
        ;;
    *)
        die "unsupported os: $OS. only linux / darwin(macos) supported."
        ;;
esac

say "target runtime: ${RID}"

# ── 1. Api.zipkey injection ───────────────────────────────────
CSPROJ="$PROJ_DIR/SKIPPY.csproj"
CONFIG_CS="$PROJ_DIR/Services/ApiConfig.g.cs"
API_ZIPKEY="$PROJ_DIR/publish/Api.zipkey"

if [ -f "$API_ZIPKEY" ]; then
    say "${CYAN}found publish/Api.zipkey — injecting api config${NC}"

    API_URL=$(sed -n '1p' "$API_ZIPKEY" | tr -d '\r\n' || true)
    API_KEY=$(sed -n '2p' "$API_ZIPKEY" | tr -d '\r\n' || true)

    if [ -n "$API_URL" ] && [ -n "$API_KEY" ]; then
        cat > "$CONFIG_CS" << EOFG
// AUTO-GENERATED by build script from publish/Api.zipkey — DO NOT EDIT
namespace SKIPPY.Services;
internal static class ApiConfig
{
    public static readonly string BaseUrl = "${API_URL}";
    public static readonly string ApiKey  = "${API_KEY}";
}
EOFG
        say "  api endpoint: ${API_URL}"
        say "  api key len: ${#API_KEY} chars"
    else
        warn "  Api.zipkey found but empty/invalid — keeping defaults"
    fi
else
    say "no publish/Api.zipkey — using default (empty) api config"
    # ensure default config exists (no-op if it's already there)
    if [ ! -f "$CONFIG_CS" ]; then
        cat > "$CONFIG_CS" << 'EOFG'
// AUTO-GENERATED — no Api.zipkey found during build
namespace SKIPPY.Services;
internal static class ApiConfig
{
    public static readonly string BaseUrl = "";
    public static readonly string ApiKey  = "";
}
EOFG
    fi
fi

# ── 2. restore ────────────────────────────────────────────────
say "restoring packages..."
dotnet restore "$CSPROJ" || die "restore failed"

# ── 3. build ──────────────────────────────────────────────────
OUT_DIR="$PROJ_DIR/publish/${RID}"

say "building for ${RID}..."
dotnet publish "$CSPROJ" \
    -c Release \
    -r "$RID" \
    --self-contained true \
    -p:PublishSingleFile=true \
    -p:DebugType=embedded \
    -o "$OUT_DIR" \
    || die "build failed"

# ── 4. copy skins ─────────────────────────────────────────────
SKIN_SRC="$PROJ_DIR/皮肤"
SKIN_DST="$OUT_DIR/皮肤"
if [ -d "$SKIN_SRC" ]; then
    say "copying skins..."
    mkdir -p "$SKIN_DST"
    cp -r "$SKIN_SRC"/* "$SKIN_DST"/ 2>/dev/null || true
    say "  $(ls -1 "$SKIN_DST"/*.png 2>/dev/null | wc -l) skin(s) ready"
fi

# copy bundled tesseract if present (Windows portable install)
TESS_SRC="$PROJ_DIR/publish/tesseract"
TESS_DST="$OUT_DIR/tesseract"
if [ -d "$TESS_SRC" ]; then
    say "copying bundled tesseract..."
    mkdir -p "$TESS_DST"
    cp -r "$TESS_SRC"/* "$TESS_DST"/ 2>/dev/null || true
    say "  tesseract bundled"
fi

# ── 5. show result ────────────────────────────────────────────
echo ""
say "build complete! → ${OUT_DIR}"

BIN="$OUT_DIR/SKIPPY"
[ -f "$BIN" ] || BIN="$OUT_DIR/SKIPPY.exe"
if [ -f "$BIN" ]; then
    say "binary: ${BIN}  ($(ls -lh "$BIN" | awk '{print $5}'))"
fi

# ── 6. compress? ──────────────────────────────────────────────
echo ""
read -r -p "$(echo -e "${GREEN}[buildit]${NC} compress output? (y/n): ")" -n 1 answer 2>/dev/null || answer="n"
echo ""

if [ "$answer" != "y" ] && [ "$answer" != "Y" ]; then
    say "skipping compression. done!"
    exit 0
fi

# find latest .zipkey
ZIPKEY_PATH=""
if [ -d "$PROJ_DIR/publish" ]; then
    # find the most recently modified .zipkey file
    ZIPKEY_PATH=$(ls -t "$PROJ_DIR"/publish/*.zipkey 2>/dev/null | grep -v 'Api\.zipkey' | head -1 || true)
fi

if [ -z "$ZIPKEY_PATH" ]; then
    warn "no .zipkey found in publish/ (excluding Api.zipkey)"
    warn "  create a publish/xxx.zipkey file containing the zip password, then re-run."
    warn "  (Api.zipkey is for api config, not zip encryption)"
    exit 0
fi

say "using zipkey: $(basename "$ZIPKEY_PATH")"
ZIP_PASS=$(head -1 "$ZIPKEY_PATH" | tr -d '\r\n')

if [ -z "$ZIP_PASS" ]; then
    warn "zipkey file is empty — skipping compression"
    exit 0
fi

# try 7z first, fall back to zip
ZIP_OUT="$PROJ_DIR/publish/${RID}.zip"

if command -v 7z >/dev/null 2>&1; then
    say "compressing with 7z..."
    7z a -p"${ZIP_PASS}" -mx=9 "$ZIP_OUT" "$OUT_DIR"/* >/dev/null || die "7z failed"
elif command -v zip >/dev/null 2>&1; then
    say "compressing with zip..."
    cd "$OUT_DIR" && zip -r -P "$ZIP_PASS" -9 "$ZIP_OUT" . >/dev/null || die "zip failed"
else
    die "neither 7z nor zip found. install one of them."
fi

say "archive created: ${ZIP_OUT}  ($(ls -lh "$ZIP_OUT" | awk '{print $5}'))"
say "all done!"
