#!/usr/bin/env bash
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
say()  { echo -e "${GREEN}[crossp]${NC} $*"; }
warn() { echo -e "${YELLOW}[crossp]${NC} $*"; }
die()  { echo -e "${RED}[crossp]${NC} $*"; exit 1; }

PROJ_DIR="$(cd "$(dirname "$0")" && pwd)"
say "cross compile: Linux → Windows x64"
say "project dir: ${PROJ_DIR}"

# ── 0. check host + dotnet ────────────────────────────────────
HOST_OS=$(uname -s)
if [ "$HOST_OS" != "Linux" ]; then
    die "this script runs on Linux, not $HOST_OS. for macOS → win, use: dotnet publish -r win-x64"
fi

say "checking dotnet sdk..."
command -v dotnet >/dev/null 2>&1 || die "dotnet sdk not found"
DOTNET_VER=$(dotnet --version 2>/dev/null || echo "???")
say "dotnet sdk: v${DOTNET_VER}"

# optional wine check
if command -v wine >/dev/null 2>&1; then
    say "wine found: $(wine --version 2>/dev/null || echo ???)"
else
    warn "wine not found — can't locally test the output .exe"
fi

WIN_RID="win-x64"

# ── 1. Api.zipkey injection ───────────────────────────────────
CSPROJ="$PROJ_DIR/SKIPPY.csproj"
CONFIG_CS="$PROJ_DIR/Services/ApiConfig.g.cs"
API_ZIPKEY="$PROJ_DIR/publish/Api.zipkey"

if [ -f "$API_ZIPKEY" ]; then
    say "${CYAN}found publish/Api.zipkey — injecting api config${NC}"

    API_URL=$(sed -n '1p' "$API_ZIPKEY" | tr -d '\r\n' || true)
    API_KEY=$(sed -n '2p' "$API_ZIPKEY" | tr -d '\r\n' || true)

    if [ -n "$API_URL" ] && [ -n "$API_KEY" ]; then
        cat > "$CONFIG_CS" << EOFG
// AUTO-GENERATED by build script from publish/Api.zipkey — DO NOT EDIT
namespace SKIPPY.Services;
internal static class ApiConfig
{
    public static readonly string BaseUrl = "${API_URL}";
    public static readonly string ApiKey  = "${API_KEY}";
}
EOFG
        say "  api endpoint: ${API_URL}"
        say "  api key len: ${#API_KEY} chars"
    else
        warn "  Api.zipkey found but empty/invalid — keeping defaults"
    fi
else
    say "no publish/Api.zipkey — using default api config"
    if [ ! -f "$CONFIG_CS" ]; then
        cat > "$CONFIG_CS" << 'EOFG'
// AUTO-GENERATED — no Api.zipkey found during build
namespace SKIPPY.Services;
internal static class ApiConfig
{
    public static readonly string BaseUrl = "";
    public static readonly string ApiKey  = "";
}
EOFG
    fi
fi

# ── 2. clean & restore ────────────────────────────────────────
say "cleaning old artifacts..."
dotnet clean "$CSPROJ" -c Release -r "$WIN_RID" >/dev/null 2>&1 || true

say "restoring packages (including windows-native)..."
dotnet restore "$CSPROJ" -r "$WIN_RID" || die "restore failed"

# ── 3. cross-publish ──────────────────────────────────────────
OUT_DIR="$PROJ_DIR/publish/${WIN_RID}"

say "cross-compiling for ${WIN_RID} (downloading windows runtime if needed)..."
dotnet publish "$CSPROJ" \
    -c Release \
    -r "$WIN_RID" \
    --self-contained true \
    -p:PublishSingleFile=true \
    -p:DebugType=embedded \
    -p:IncludeNativeLibrariesForSelfExtract=true \
    -o "$OUT_DIR" \
    || die "cross-compile failed"

say "publish complete!"

# ── 4. copy skins ─────────────────────────────────────────────
SKIN_SRC="$PROJ_DIR/皮肤"
SKIN_DST="$OUT_DIR/皮肤"
if [ -d "$SKIN_SRC" ]; then
    say "copying skins..."
    mkdir -p "$SKIN_DST"
    cp -r "$SKIN_SRC"/* "$SKIN_DST"/ 2>/dev/null || true
    say "  $(ls -1 "$SKIN_DST"/*.png 2>/dev/null | wc -l) skin(s) ready"
fi

# ── 5. result ─────────────────────────────────────────────────
echo ""
EXE_PATH="$OUT_DIR/SKIPPY.exe"
if [ -f "$EXE_PATH" ]; then
    say "SUCCESS → ${EXE_PATH}  ($(ls -lh "$EXE_PATH" | awk '{print $5}'))"
    say "copy 'publish/${WIN_RID}' folder to a Windows machine and run SKIPPY.exe"
else
    die "output binary not found at $EXE_PATH"
fi

# ── 6. compress? ──────────────────────────────────────────────
echo ""
read -r -p "$(echo -e "${GREEN}[crossp]${NC} compress output? (y/n): ")" -n 1 answer 2>/dev/null || answer="n"
echo ""

if [ "$answer" != "y" ] && [ "$answer" != "Y" ]; then
    say "skipping compression. done!"
    exit 0
fi

# find latest .zipkey (excluding Api.zipkey)
ZIPKEY_PATH=""
if [ -d "$PROJ_DIR/publish" ]; then
    ZIPKEY_PATH=$(ls -t "$PROJ_DIR"/publish/*.zipkey 2>/dev/null | grep -v 'Api\.zipkey' | head -1 || true)
fi

if [ -z "$ZIPKEY_PATH" ]; then
    warn "no .zipkey found in publish/ (excluding Api.zipkey)"
    warn "  create a publish/xxx.zipkey with the password on line 1, then re-run."
    exit 0
fi

say "using zipkey: $(basename "$ZIPKEY_PATH")"
ZIP_PASS=$(head -1 "$ZIPKEY_PATH" | tr -d '\r\n')

if [ -z "$ZIP_PASS" ]; then
    warn "zipkey file is empty — skipping compression"
    exit 0
fi

ZIP_OUT="$PROJ_DIR/publish/${WIN_RID}.zip"

if command -v 7z >/dev/null 2>&1; then
    say "compressing with 7z..."
    7z a -p"${ZIP_PASS}" -mx=9 "$ZIP_OUT" "$OUT_DIR"/* >/dev/null || die "7z failed"
elif command -v zip >/dev/null 2>&1; then
    say "compressing with zip..."
    cd "$OUT_DIR" && zip -r -P "$ZIP_PASS" -9 "$ZIP_OUT" . >/dev/null || die "zip failed"
else
    die "neither 7z nor zip found. install one of them."
fi

say "archive created: ${ZIP_OUT}  ($(ls -lh "$ZIP_OUT" | awk '{print $5}'))"
say "all done!"
